name: CI

on:
  push:
    branches:
    - master

  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - uses: leafo/gh-actions-lua@v5
      with:
        luaVersion: "5.1"

    - uses: leafo/gh-actions-luarocks@v2

    - name: Install dependencies
      run: |
        luarocks install luafilesystem
        luarocks install luacheck

    - uses: rojo-rbx/setup-foreman@v1
      with:
        version: "^1.0.0"
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Test
      run: |
        ./script/test.sh
        luacheck src
